module.exports = {
  ADMIN_LOAD_APPLICATIONS: 'ADMIN_LOAD_APPLICATIONS',
  ADMIN_LOAD_APPLICATIONS_SUCCESS: 'ADMIN_LOAD_APPLICATIONS_SUCCESS',
  ADMIN_LOAD_APPLICATIONS_ERROR: 'ADMIN_LOAD_APPLICATIONS_ERROR',

  ADMIN_APPROVE_APPLICATION: 'ADMIN_APPROVE_APPLICATION',
  ADMIN_APPROVE_APPLICATION_SUCCESS: 'ADMIN_APPROVE_APPLICATION_SUCCESS',
  ADMIN_APPROVE_APPLICATION_ERROR: 'ADMIN_APPROVE_APPLICATION_ERROR',

  ADMIN_REJECT_APPLICATION: 'ADMIN_REJECT_APPLICATION',
  ADMIN_REJECT_APPLICATION_SUCCESS: 'ADMIN_REJECT_APPLICATION_SUCCESS',
  ADMIN_REJECT_APPLICATION_ERROR: 'ADMIN_REJECT_APPLICATION_ERROR'
};
