module.exports = {
  CANDIDATE_SIGN_UP: 'CANDIDATE_SIGN_UP',
  CANDIDATE_SIGN_UP_SUCCESS: 'CANDIDATE_SIGN_UP_SUCCESS',
  CANDIDATE_SIGN_UP_ERROR: 'CANDIDATE_SIGN_UP_ERROR',

  CANDIDATE_LOAD_EMPLOYERS: 'CANDIDATE_LOAD_EMPLOYERS',
  CANDIDATE_LOAD_EMPLOYERS_SUCCESS: 'CANDIDATE_LOAD_EMPLOYERS_SUCCESS',
  CANDIDATE_LOAD_EMPLOYERS_ERROR: 'CANDIDATE_LOAD_EMPLOYERS_ERROR',

  CANDIDATE_LOAD_MENTORS: 'CANDIDATE_LOAD_MENTORS',
  CANDIDATE_LOAD_MENTORS_SUCCESS: 'CANDIDATE_LOAD_MENTORS_SUCCESS',
  CANDIDATE_LOAD_MENTORS_ERROR: 'CANDIDATE_LOAD_MENTORS_ERROR',  

  CANDIDATE_LOAD_MENTOR_TASKS: 'CANDIDATE_LOAD_MENTOR_TASKS',
  CANDIDATE_LOAD_MENTOR_TASKS_SUCCESS: 'CANDIDATE_LOAD_MENTOR_TASKS_SUCCESS',
  CANDIDATE_LOAD_MENTOR_TASKS_ERROR: 'CANDIDATE_LOAD_MENTOR_TASKS_ERROR', 

  CANDIDATE_LOAD_MYVOUCHERS: 'CANDIDATE_LOAD_MYVOUCHERS',
  CANDIDATE_LOAD_MYVOUCHERS_SUCCESS: 'CANDIDATE_LOAD_MYVOUCHERS_SUCCESS',
  CANDIDATE_LOAD_MYVOUCHERS_ERROR: 'CANDIDATE_LOAD_MYVOUCHERS_ERROR',

  CANDIDATE_CHALLENGE_TASK: 'CANDIDATE_CHALLENGE_TASK',
  CANDIDATE_CHALLENGE_TASK_SUCCESS: 'CANDIDATE_CHALLENGE_TASK_SUCCESS',
  CANDIDATE_CHALLENGE_TASK_ERROR: 'CANDIDATE_CHALLENGE_TASK_ERROR',
  
  CANDIDATE_EMPLOYER_JOBS: 'CANDIDATE_EMPLOYER_JOBS',
  CANDIDATE_EMPLOYER_JOBS_SUCCESS: 'CANDIDATE_EMPLOYER_JOBS_SUCCESS',
  CANDIDATE_EMPLOYER_JOBS_ERROR: 'CANDIDATE_EMPLOYER_JOBS_ERROR',

  CANDIDATE_APPLY_JOB: 'CANDIDATE_APPLY_JOB',
  CANDIDATE_APPLY_JOB_SUCCESS: 'CANDIDATE_APPLY_JOB_SUCCESS',
  CANDIDATE_APPLY_JOB_ERROR: 'CANDIDATE_APPLY_JOB_ERROR',

  CANDIDATE_LOAD_TASK_CHALLENGES: 'CANDIDATE_LOAD_TASK_CHALLENGES',
  CANDIDATE_LOAD_TASK_CHALLENGES_ERROR: 'CANDIDATE_LOAD_TASK_CHALLENGES_ERROR',
  CANDIDATE_LOAD_TASK_CHALLENGES_SUCCESS: 'CANDIDATE_LOAD_TASK_CHALLENGES_SUCCESS',

  CANDIDATE_GET_TASK_TEMPLATE: 'CANDIDATE_GET_TASK_TEMPLATE',
  CANDIDATE_GET_TASK_TEMPLATE_ERROR: 'CANDIDATE_GET_TASK_TEMPLATE_ERROR',
  CANDIDATE_GET_TASK_TEMPLATE_SUCCESS: 'CANDIDATE_GET_TASK_TEMPLATE_SUCCESS',

  CANDIDATE_SUBMIT_SOLUTION_FILE: 'CANDIDATE_SUBMIT_SOLUTION_FILE',
  CANDIDATE_SUBMIT_SOLUTION_FILE_ERROR: 'CANDIDATE_SUBMIT_SOLUTION_FILE_ERROR',
  CANDIDATE_SUBMIT_SOLUTION_FILE_SUCCESS: 'CANDIDATE_SUBMIT_SOLUTION_FILE_SUCCESS',

  CANDIDATE_PAY_CHALLENGE_ERROR: 'CANDIDATE_PAY_CHALLENGE_ERROR',
  CANDIDATE_PAY_CHALLENGE_SUCCESS: 'CANDIDATE_PAY_CHALLENGE_SUCCESS',
  CANDIDATE_PAY_CHALLENGE: 'CANDIDATE_PAY_CHALLENGE',

  CANDIDATE_REVIEW_MENTOR_ERROR: 'CANDIDATE_REVIEW_MENTOR_ERROR',
  CANDIDATE_REVIEW_MENTOR_SUCCESS: 'CANDIDATE_REVIEW_MENTOR_SUCCESS',
  CANDIDATE_REVIEW_MENTOR: 'CANDIDATE_REVIEW_MENTOR',

  CHECKIF_CANDIDATE_ALREADY_CHALLENGE_ERROR: 'CHECKIF_CANDIDATE_ALREADY_CHALLENGE_ERROR',
  CHECKIF_CANDIDATE_ALREADY_CHALLENGE_SUCCESS: 'CHECKIF_CANDIDATE_ALREADY_CHALLENGE_SUCCESS',
  CHECKIF_CANDIDATE_ALREADY_CHALLENGE: 'CHECKIF_CANDIDATE_ALREADY_CHALLENGE',

  GET_USER_PUBLIC_ERROR: 'GET_USER_PUBLIC_ERROR',
  GET_USER_PUBLIC_SUCCESS: 'GET_USER_PUBLIC_SUCCESS',
  GET_USER_PUBLIC: 'GET_USER_PUBLIC',

  GET_JOBS_ERROR: 'GET_JOBS_ERROR',
  GET_JOBS_SUCCESS: 'GET_JOBS_SUCCESS',
  GET_JOBS: 'GET_JOBS',

  CANDIDATE_GET_TASK_TEMPLATES: 'CANDIDATE_GET_TASK_TEMPLATES',
  CANDIDATE_GET_TASK_TEMPLATES_ERROR: 'CANDIDATE_GET_TASK_TEMPLATES_ERROR',
  CANDIDATE_GET_TASK_TEMPLATES_SUCCESS: 'CANDIDATE_GET_TASK_TEMPLATES_SUCCESS'
};
