module.exports = {
  COMMON_USER_RESET_PASSWORD: 'COMMON_USER_RESET_PASSWORD',
  COMMON_USER_RESET_PASSWORD_SUCCESS: 'COMMON_USER_RESET_PASSWORD_SUCCESS',
  COMMON_USER_RESET_PASSWORD_ERROR: 'COMMON_USER_RESET_PASSWORD_ERROR',

  GET_PUBLIC_USER_PROFILE: 'GET_PUBLIC_USER_PROFILE_QUERY',
  GET_PUBLIC_USER_PROFILE_SUCCESS: 'GET_PUBLIC_USER_PROFILE_SUCCESS',
  GET_PUBLIC_USER_PROFILE_ERROR: 'GET_PUBLIC_USER_PROFILE_ERROR',

  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',

  USER_UPDATE: 'USER_UPDATE',
  USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  USER_UPDATE_ERROR: 'USER_UPDATE_ERROR',

  GET_USER: 'GET_USER',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_ERROR: 'GET_USER_ERROR',

  GET_USER_RECENT_CHALLENGES: 'GET_USER_RECENT_CHALLENGES',
  GET_USER_RECENT_CHALLENGES_SUCCESS: 'GET_USER_RECENT_CHALLENGES_SUCCESS',
  GET_USER_RECENT_CHALLENGES_ERROR: 'GET_USER_RECENT_CHALLENGES_ERROR',

  LOAD_ALL_CHALLENGES_ERROR: 'LOAD_ALL_CHALLENGES_ERROR',
  LOAD_ALL_CHALLENGES_SUCCESS: 'LOAD_ALL_CHALLENGES_SUCCESS',
  LOAD_ALL_CHALLENGES: 'LOAD_ALL_CHALLENGES'  
};
