module.exports = {
  EMPLOYER_SIGN_UP: 'EMPLOYER_SIGN_UP',
  EMPLOYER_SIGN_UP_SUCCESS: 'EMPLOYER_SIGN_UP_SUCCESS',
  EMPLOYER_SIGN_UP_ERROR: 'EMPLOYER_SIGN_UP_ERROR',

  EMPLOYER_LOAD_MYJOBS_SUCCESS: 'EMPLOYER_LOAD_MYJOBS_SUCCESS',
  EMPLOYER_LOAD_MYJOBS_ERROR: 'EMPLOYER_LOAD_MYJOBS_ERROR',

  EMPLOYER_DELETE_JOB_ERROR: 'EMPLOYER_DELETE_JOB_ERROR',
  EMPLOYER_DELETE_JOB_SUCCESS: 'EMPLOYER_DELETE_JOB_SUCCESS',

  EMPLOYER_LOAD_JOB_APPLICATIONS_ERROR: 'EMPLOYER_LOAD_JOB_APPLICATIONS_ERROR',
  EMPLOYER_LOAD_JOB_APPLICATIONS_SUCCESS: 'EMPLOYER_LOAD_JOB_APPLICATIONS_SUCCESS',

  EMPLOYER_UPDATE_PROFILE_ERROR: 'EMPLOYER_UPDATE_PROFILE_ERROR',
  EMPLOYER_UPDATE_PROFILE_SUCCESS: 'EMPLOYER_UPDATE_PROFILE_SUCCESS',

  GET_PUBLIC_USER_PROFILE_SUCCESS: 'GET_PUBLIC_USER_PROFILE_SUCCESS',
  GET_PUBLIC_USER_PROFILE_ERROR: 'GET_PUBLIC_USER_PROFILE_ERROR',

  EMPLOYER_CREATE_JOB_SUCCESS: 'EMPLOYER_CREATE_JOB_SUCCESS',
  EMPLOYER_CREATE_JOB_ERROR: 'EMPLOYER_CREATE_JOB_ERROR',

  EMPLOYER_UPDATE_JOB_SUCCESS: 'EMPLOYER_UPDATE_JOB_SUCCESS',
  EMPLOYER_UPDATE_JOB_ERROR: 'EMPLOYER_UPDATE_JOB_ERROR'
};
