module.exports = {
  MENTOR_SIGN_UP: 'MENTOR_SIGN_UP',
  MENTOR_SIGN_UP_SUCCESS: 'MENTOR_SIGN_UP_SUCCESS',
  MENTOR_SIGN_UP_ERROR: 'MENTOR_SIGN_UP_ERROR',

  MENTOR_LOAD_TASKS: 'MENTOR_LOAD_TASKS',
  MENTOR_LOAD_TASKS_SUCCESS: 'MENTOR_LOAD_TASKS_SUCCESS',
  MENTOR_LOAD_TASKS_ERROR: 'MENTOR_LOAD_TASKS_ERROR',

  MENTOR_LINK_STRIPE: 'MENTOR_LINK_STRIPE',
  MENTOR_LINK_STRIPE_SUCCESS: 'MENTOR_LINK_STRIPE_SUCCESS',
  MENTOR_LINK_STRIPE_ERROR: 'MENTOR_LINK_STRIPE_ERROR',

  MENTOR_SAVE_STRIPE: 'MENTOR_SAVE_STRIPE',
  MENTOR_SAVE_STRIPE_SUCCESS: 'MENTOR_SAVE_STRIPE_SUCCESS',
  MENTOR_SAVE_STRIPE_ERROR: 'MENTOR_SAVE_STRIPE_ERROR',

  MENTOR_LOAD_MYCHALLENGES_SUCCESS: 'MENTOR_LOAD_MYCHALLENGES_SUCCESS',
  MENTOR_LOAD_MYCHALLENGES_ERROR: 'MENTOR_LOAD_MYCHALLENGES_ERROR',

  MENTOR_REVIEW_CHALLENGE_SUCCESS: 'MENTOR_REVIEW_CHALLENGE_SUCCESS',
  MENTOR_REVIEW_CHALLENGE_ERROR: 'MENTOR_REVIEW_CHALLENGE_ERROR',

  MENTOR_ASK_RESUBMIT_SUCCESS: 'MENTOR_ASK_RESUBMIT_SUCCESS',
  MENTOR_ASK_RESUBMIT_ERROR: 'MENTOR_ASK_RESUBMIT_ERROR'
};
